import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import prisma from "../utils/db";
import Table from "../components/Table";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ items = [] }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <Table items={items} />
        </div>
      </main>
    </>
  );
}

export async function getServerSideProps() {
  const items = await prisma.item.findMany();
  return {
    props: {
      items: JSON.parse(JSON.stringify(items)),
    },
  };
}
